version: 0.0
os: linux
files:
  - source: /app.js
    destination: /var/www/html/code2
hooks:
  BeforeInstall:
    - location: Scripts/install_dependencies
      timeout: 300
      runas: root
    - location: Scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: Scripts/stop_server
      timeout: 300
      runas: root
